version: '3'

# Command-line
# https://docs.docker.com/compose/reference/

services:
  db:
    image: mysql:5.6
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_ROOT_PASSWORD: wordpress
    volumes:
      - ./docker/data:/var/lib/mysql
    ports:
    - "3306:3306"

  php:
    build: .
    ports:
      - 8080:80
    depends_on:
    - db
    volumes:
      - ./docker/php/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
      - ./docker/apache2/httpd-vhosts.conf:/etc/apache2/sites-enabled/000-default.conf
      - ./app/public:/var/www/html
    environment:
      DB_NAME: wordpress
      DB_USER: root
      DB_PASSWORD: wordpress
      DB_HOST: db
      WP_DEBUG: 1

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    ports:
      - 8081:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
    restart: always
    depends_on:
      - db